version: '3.7'

services:
  # frontend:
  #   build:
  #     context: .
  #     dockerfile: ./packages/frontend/Dockerfile
  #   restart: always
  #   ports:
  #     - 8080:80

  # backend:
  #   build:
  #     context: .
  #     dockerfile: ./packages/backend/Dockerfile
  #   restart: always
  #   ports:
  #     - 4000:4000

  database:
    image: mysql:5.7.28
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bike_shop
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    ports:
      - 3306:3306

volumes:
  mysql_data: {}
