-- MySQL Script generated by MySQL Workbench
-- Wed Mar  3 10:18:35 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`categories` (
  `category_id` VARCHAR(32) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NULL,
  `url_slug` VARCHAR(100) NULL,
  `description` TEXT(1000) NULL,
  `sabcategory_id` VARCHAR(32) NOT NULL,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  PRIMARY KEY (`category_id`));


-- -----------------------------------------------------
-- Table `mydb`.`category_images`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`category_images` (
  `category_image_id` VARCHAR(32) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NULL,
  `image` LONGBLOB NULL,
  `category_id` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`category_image_id`),
  INDEX `fk_category_images_categories1_idx` (`category_id` ASC) VISIBLE,
  CONSTRAINT `fk_category_images_categories1`
    FOREIGN KEY (`category_id`)
    REFERENCES `mydb`.`categories` (`category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`orders` (
  `order_id` VARCHAR(32) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `update_at` DATETIME NULL,
  `total_price` FLOAT NULL DEFAULT 0,
  PRIMARY KEY (`order_id`));


-- -----------------------------------------------------
-- Table `mydb`.`product_images`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`product_images` (
  `product_image_id` VARCHAR(32) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NULL,
  `image` LONGBLOB NULL,
  `product_id` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`product_image_id`),
  INDEX `fk_product_images_products1_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_product_images_products1`
    FOREIGN KEY (`product_id`)
    REFERENCES `mydb`.`products` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`products` (
  `product_id` VARCHAR(32) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NULL,
  `name` VARCHAR(255) NOT NULL,
  `price` FLOAT NULL,
  `description` TEXT(1000) NULL,
  `url_slug` VARCHAR(100) NULL,
  `category_id` VARCHAR(32) NOT NULL,
  `subcategory_id` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`product_id`),
  INDEX `fk_products_categories1_idx` (`category_id` ASC) VISIBLE,
  INDEX `fk_products_subcategories1_idx` (`subcategory_id` ASC) VISIBLE,
  CONSTRAINT `fk_products_categories1`
    FOREIGN KEY (`category_id`)
    REFERENCES `mydb`.`categories` (`category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_products_subcategories1`
    FOREIGN KEY (`subcategory_id`)
    REFERENCES `mydb`.`subcategories` (`subcategory_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`subcategories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`subcategories` (
  `subcategory_id` VARCHAR(32) NOT NULL,
  `created_at` DATETIME GENERATED ALWAYS AS (),
  `updated_at` DATETIME GENERATED ALWAYS AS (),
  `name` VARCHAR(100) NOT NULL,
  `url_slug` VARCHAR(100) NULL,
  `description` TEXT(1000) NULL,
  `parent_category_id` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`subcategory_id`),
  INDEX `fk_subcategories_categories1_idx` (`parent_category_id` ASC) VISIBLE,
  CONSTRAINT `fk_subcategories_categories1`
    FOREIGN KEY (`parent_category_id`)
    REFERENCES `mydb`.`categories` (`category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`subcategory_images`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`subcategory_images` (
  `subcategory_image_id` VARCHAR(32) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NULL,
  `image` LONGBLOB NULL,
  `subcategory_id` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`subcategory_image_id`),
  INDEX `fk_subcategory_images_subcategories1_idx` (`subcategory_id` ASC) VISIBLE,
  CONSTRAINT `fk_subcategory_images_subcategories1`
    FOREIGN KEY (`subcategory_id`)
    REFERENCES `mydb`.`subcategories` (`subcategory_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user_images`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user_images` (
  `user_image_id` VARCHAR(32) NOT NULL,
  `image` VARCHAR(45) NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NULL,
  `user_id` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`user_image_id`),
  INDEX `fk_user_images_users1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_images_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `user_id` VARCHAR(32) NOT NULL,
  `username` VARCHAR(16) NULL,
  `email` VARCHAR(100) NOT NULL,
  `password_hash` VARCHAR(100) NOT NULL,
  `updated_at` DATETIME GENERATED ALWAYS AS (),
  `created_at` DATETIME GENERATED ALWAYS AS (),
  `role` VARCHAR(20) NOT NULL,
  `order_id` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `fk_users_orders_idx` (`order_id` ASC) VISIBLE,
  CONSTRAINT `fk_users_orders`
    FOREIGN KEY (`order_id`)
    REFERENCES `mydb`.`orders` (`order_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
